/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package temperaturecontroller;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JTextField;
import variables.variables;


/**
 *
 * @author ajevi
 */
public class tempui extends javax.swing.JFrame {

    /**
     * Creates new form tempui
     */
    public tempui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        setrate1 = new javax.swing.JTextField();
        settemp1 = new javax.swing.JTextField();
        rate1up = new javax.swing.JButton();
        rate1down = new javax.swing.JButton();
        temp1up = new javax.swing.JButton();
        temp1down = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LED1 = new javax.swing.JLabel();
        process1toggle = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        setrate2 = new javax.swing.JTextField();
        settemp2 = new javax.swing.JTextField();
        rate2up = new javax.swing.JButton();
        rate2down = new javax.swing.JButton();
        temp2up = new javax.swing.JButton();
        temp2down = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        LED2 = new javax.swing.JLabel();
        process2toggle = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        setrate3 = new javax.swing.JTextField();
        settemp3 = new javax.swing.JTextField();
        rate3up = new javax.swing.JButton();
        rate3down = new javax.swing.JButton();
        temp3up = new javax.swing.JButton();
        temp3down = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        LED3 = new javax.swing.JLabel();
        process3toggle = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        temp1 = new javax.swing.JTextField();
        temp2 = new javax.swing.JTextField();
        temp6 = new javax.swing.JTextField();
        temp3 = new javax.swing.JTextField();
        temp5 = new javax.swing.JTextField();
        temp4 = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Zone 1"));

        setrate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                setrate1MousePressed(evt);
            }
        });
        setrate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setrate1ActionPerformed(evt);
            }
        });

        settemp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settemp1ActionPerformed(evt);
            }
        });

        rate1up.setText("+");
        rate1up.setToolTipText("");
        rate1up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rate1upMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rate1upMouseReleased(evt);
            }
        });
        rate1up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate1upActionPerformed(evt);
            }
        });

        rate1down.setText("-");

        temp1up.setText("+");
        temp1up.setToolTipText("");
        temp1up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                temp1upMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                temp1upMouseReleased(evt);
            }
        });
        temp1up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temp1upActionPerformed(evt);
            }
        });

        temp1down.setText("-");

        jLabel6.setText("Rate");

        jLabel7.setText("Temp");

        LED1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LED1.setText("●");

        process1toggle.setText("ON/OFF");
        process1toggle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                process1toggleItemStateChanged(evt);
            }
        });
        process1toggle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                process1toggleStateChanged(evt);
            }
        });
        process1toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                process1toggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LED1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(settemp1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(setrate1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(temp1up)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(temp1down))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rate1up)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rate1down)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(process1toggle, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LED1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rate1up)
                                    .addComponent(rate1down))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(temp1up)
                                    .addComponent(temp1down)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(setrate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(settemp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(process1toggle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Zone 2"));

        setrate2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                setrate2MousePressed(evt);
            }
        });
        setrate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setrate2ActionPerformed(evt);
            }
        });

        settemp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settemp2ActionPerformed(evt);
            }
        });

        rate2up.setText("+");
        rate2up.setToolTipText("");
        rate2up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rate2upMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rate2upMouseReleased(evt);
            }
        });
        rate2up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate2upActionPerformed(evt);
            }
        });

        rate2down.setText("-");

        temp2up.setText("+");
        temp2up.setToolTipText("");
        temp2up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                temp2upMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                temp2upMouseReleased(evt);
            }
        });
        temp2up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temp2upActionPerformed(evt);
            }
        });

        temp2down.setText("-");

        jLabel13.setText("Rate");

        jLabel14.setText("Temp");

        LED2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LED2.setText("●");

        process2toggle.setText("ON/OFF");
        process2toggle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                process2toggleItemStateChanged(evt);
            }
        });
        process2toggle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                process2toggleStateChanged(evt);
            }
        });
        process2toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                process2toggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(LED2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(settemp2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(setrate2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(temp2up)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(temp2down))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(rate2up)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rate2down)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(process2toggle, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(LED2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rate2up)
                            .addComponent(rate2down))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(temp2up)
                            .addComponent(temp2down)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setrate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(settemp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(process2toggle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Zone 3"));

        setrate3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                setrate3MousePressed(evt);
            }
        });
        setrate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setrate3ActionPerformed(evt);
            }
        });

        settemp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settemp3ActionPerformed(evt);
            }
        });

        rate3up.setText("+");
        rate3up.setToolTipText("");
        rate3up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rate3upMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rate3upMouseReleased(evt);
            }
        });
        rate3up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate3upActionPerformed(evt);
            }
        });

        rate3down.setText("-");

        temp3up.setText("+");
        temp3up.setToolTipText("");
        temp3up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                temp3upMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                temp3upMouseReleased(evt);
            }
        });
        temp3up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temp3upActionPerformed(evt);
            }
        });

        temp3down.setText("-");

        jLabel15.setText("Rate");

        jLabel16.setText("Temp");

        LED3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LED3.setText("●");

        process3toggle.setText("ON/OFF");
        process3toggle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                process3toggleItemStateChanged(evt);
            }
        });
        process3toggle.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                process3toggleStateChanged(evt);
            }
        });
        process3toggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                process3toggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(LED3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(settemp3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(setrate3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(temp3up)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(temp3down))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(rate3up)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rate3down)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(process3toggle, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(LED3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rate3up)
                            .addComponent(rate3down))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(temp3up)
                            .addComponent(temp3down)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setrate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(settemp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(process3toggle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thermocouple Readings"));

        temp1.setText("jTextField4");

        temp2.setText("jTextField8");

        temp6.setText("jTextField9");

        temp3.setText("jTextField10");

        temp5.setText("jTextField11");
        temp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temp5ActionPerformed(evt);
            }
        });

        temp4.setText("jTextField12");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(temp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(temp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(temp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(temp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(temp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(temp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void process1toggleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_process1toggleStateChanged
        
    }//GEN-LAST:event_process1toggleStateChanged

    private void process1toggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_process1toggleActionPerformed
    
    }//GEN-LAST:event_process1toggleActionPerformed

    private void process1toggleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_process1toggleItemStateChanged

    }//GEN-LAST:event_process1toggleItemStateChanged

    private void setrate1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setrate1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_setrate1MousePressed

    private void setrate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setrate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setrate1ActionPerformed

    private void settemp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settemp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settemp1ActionPerformed

    private void rate1upMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rate1upMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rate1upMousePressed

    private void rate1upMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rate1upMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_rate1upMouseReleased

    private void rate1upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate1upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rate1upActionPerformed

    private void temp1upMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temp1upMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_temp1upMousePressed

    private void temp1upMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temp1upMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_temp1upMouseReleased

    private void temp1upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temp1upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temp1upActionPerformed

    private void setrate2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setrate2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_setrate2MousePressed

    private void setrate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setrate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setrate2ActionPerformed

    private void settemp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settemp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settemp2ActionPerformed

    private void rate2upMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rate2upMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rate2upMousePressed

    private void rate2upMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rate2upMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_rate2upMouseReleased

    private void rate2upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate2upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rate2upActionPerformed

    private void temp2upMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temp2upMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_temp2upMousePressed

    private void temp2upMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temp2upMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_temp2upMouseReleased

    private void temp2upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temp2upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temp2upActionPerformed

    private void setrate3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setrate3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_setrate3MousePressed

    private void setrate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setrate3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setrate3ActionPerformed

    private void settemp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settemp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settemp3ActionPerformed

    private void rate3upMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rate3upMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rate3upMousePressed

    private void rate3upMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rate3upMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_rate3upMouseReleased

    private void rate3upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate3upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rate3upActionPerformed

    private void temp3upMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temp3upMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_temp3upMousePressed

    private void temp3upMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temp3upMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_temp3upMouseReleased

    private void temp3upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temp3upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temp3upActionPerformed

    private void process2toggleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_process2toggleItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_process2toggleItemStateChanged

    private void process2toggleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_process2toggleStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_process2toggleStateChanged

    private void process2toggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_process2toggleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_process2toggleActionPerformed

    private void process3toggleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_process3toggleItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_process3toggleItemStateChanged

    private void process3toggleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_process3toggleStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_process3toggleStateChanged

    private void process3toggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_process3toggleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_process3toggleActionPerformed

    private void temp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temp5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temp5ActionPerformed

    public JLabel getLED1() {
        return LED1;
    }

    public void setLED1(JLabel LED1) {
        this.LED1 = LED1;
    }

    public JLabel getLED2() {
        return LED2;
    }

    public void setLED2(JLabel LED2) {
        this.LED2 = LED2;
    }

    public JLabel getLED3() {
        return LED3;
    }

    public void setLED3(JLabel LED3) {
        this.LED3 = LED3;
    }

    public JTextField getSetrate1() {
        return setrate1;
    }

    public void setSetrate1(JTextField setrate1) {
        this.setrate1 = setrate1;
    }

    public JTextField getSetrate2() {
        return setrate2;
    }

    public void setSetrate2(JTextField setrate2) {
        this.setrate2 = setrate2;
    }

    public JTextField getSetrate3() {
        return setrate3;
    }

    public void setSetrate3(JTextField setrate3) {
        this.setrate3 = setrate3;
    }

    public JTextField getSettemp1() {
        return settemp1;
    }

    public void setSettemp1(JTextField settemp1) {
        this.settemp1 = settemp1;
    }

    public JTextField getSettemp2() {
        return settemp2;
    }

    public void setSettemp2(JTextField settemp2) {
        this.settemp2 = settemp2;
    }

    public JTextField getSettemp3() {
        return settemp3;
    }

    public void setSettemp3(JTextField settemp3) {
        this.settemp3 = settemp3;
    }

    public JTextField getTemp1() {
        return temp1;
    }

    public void setTemp1(JTextField temp1) {
        this.temp1 = temp1;
    }

    public JTextField getTemp2() {
        return temp2;
    }

    public void setTemp2(JTextField temp2) {
        this.temp2 = temp2;
    }

    public JTextField getTemp3() {
        return temp3;
    }

    public void setTemp3(JTextField temp3) {
        this.temp3 = temp3;
    }

    public JTextField getTemp4() {
        return temp4;
    }

    public void setTemp4(JTextField temp4) {
        this.temp4 = temp4;
    }

    public JTextField getTemp5() {
        return temp5;
    }

    public void setTemp5(JTextField temp5) {
        this.temp5 = temp5;
    }

    public JTextField getTemp6() {
        return temp6;
    }

    public void setTemp6(JTextField temp6) {
        this.temp6 = temp6;
    }

    /**
     * @param args the command line arguments
     */
    public static void GUI() {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tempui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tempui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tempui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tempui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tempui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LED1;
    private javax.swing.JLabel LED2;
    private javax.swing.JLabel LED3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JToggleButton process1toggle;
    private javax.swing.JToggleButton process2toggle;
    private javax.swing.JToggleButton process3toggle;
    private javax.swing.JButton rate1down;
    private javax.swing.JButton rate1up;
    private javax.swing.JButton rate2down;
    private javax.swing.JButton rate2up;
    private javax.swing.JButton rate3down;
    private javax.swing.JButton rate3up;
    private javax.swing.JTextField setrate1;
    private javax.swing.JTextField setrate2;
    private javax.swing.JTextField setrate3;
    private javax.swing.JTextField settemp1;
    private javax.swing.JTextField settemp2;
    private javax.swing.JTextField settemp3;
    private javax.swing.JTextField temp1;
    private javax.swing.JButton temp1down;
    private javax.swing.JButton temp1up;
    private javax.swing.JTextField temp2;
    private javax.swing.JButton temp2down;
    private javax.swing.JButton temp2up;
    private javax.swing.JTextField temp3;
    private javax.swing.JButton temp3down;
    private javax.swing.JButton temp3up;
    private javax.swing.JTextField temp4;
    private javax.swing.JTextField temp5;
    private javax.swing.JTextField temp6;
    // End of variables declaration//GEN-END:variables
}
